### ISSUE TITLE
Issue: Registering as Participant 

### ISSUE THREAD

**Issue by nicomartin628** [Impact-Hub-Manila/impact-hackathon-issues#1]
July 12, 8:05AM 

Upon registering as participant, inputting the phone number does not work. 
Even if there is the '+63' designation, it does not allow registrants to continue with the registration process.

**Comment by ayo-run** [comment]
Hmm Was there a red validation error text (Not a valid mobile number...) under the "Mobile no" field?

It's possible that there is another validation error in the form. Might be the checkboxes at the bottom?

**Comment by nicomartin628** [comment]
Not the check boxes eh. It was the Mobile no field. It said 'Not a valid mobile number...'

Anyway, I checked it again, it works well now! Thanks!

**Comment by ayo-run** [comment]
Closing this now as it is resolved.
